#!/usr/bin/env python

import argparse
import optparse
import os
import sys
import dill

sys.path.append(os.getcwd())

from species_distribution.main import main

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('-f', '--force', action='store_true', help='overwrite any existing output')
    parser.add_argument('-t', '--taxon', type=int, action='append', help='process this taxon only, can specify multiple -t options')
    parser.add_argument('-l', '--limit', type=int, help='process this many taxa only')
    parser.add_argument('-p', '--processes', type=int, default=1, help='use N processes')
    parser.add_argument('-e', '--numpy_exception', action='store_true', help='numpy should throws exceptions instead of logging warnings')
    parser.add_argument('-v', '--verbose', action='store_true', help='be verbose')
    parser.add_argument('-o', '--options', help='dill-produced options file')
    return parser.parse_args()

if __name__ == '__main__':
    args = parse_args()

    if args.options:
        with open(args.options, 'rb') as f:
            args = optparse.Values(dill.load(f))

    main(args)
