update allocation.allocation_data ad set gear_type_id =	800	where ad.gear_type_id =	0 ;
update allocation.allocation_data ad set gear_type_id =	301	where ad.gear_type_id =	1 ;
update allocation.allocation_data ad set gear_type_id =	301	where ad.gear_type_id =	2 ;
update allocation.allocation_data ad set gear_type_id =	301	where ad.gear_type_id =	3 ;
update allocation.allocation_data ad set gear_type_id =	301	where ad.gear_type_id =	4 ;
update allocation.allocation_data ad set gear_type_id =	301	where ad.gear_type_id =	5 ;
update allocation.allocation_data ad set gear_type_id =	301	where ad.gear_type_id =	6 ;
update allocation.allocation_data ad set gear_type_id =	800	where ad.gear_type_id =	7 ;
update allocation.allocation_data ad set gear_type_id =	302	where ad.gear_type_id =	8 ;
update allocation.allocation_data ad set gear_type_id =	302	where ad.gear_type_id =	9 ;
update allocation.allocation_data ad set gear_type_id =	500	where ad.gear_type_id =	10;
update allocation.allocation_data ad set gear_type_id =	500	where ad.gear_type_id =	11;
update allocation.allocation_data ad set gear_type_id =	606	where ad.gear_type_id =	12;
update allocation.allocation_data ad set gear_type_id =	500	where ad.gear_type_id =	13;
update allocation.allocation_data ad set gear_type_id =	500	where ad.gear_type_id =	14;
update allocation.allocation_data ad set gear_type_id =	500	where ad.gear_type_id =	15;
update allocation.allocation_data ad set gear_type_id =	303	where ad.gear_type_id =	16;
update allocation.allocation_data ad set gear_type_id =	300	where ad.gear_type_id =	17;
update allocation.allocation_data ad set gear_type_id =	303	where ad.gear_type_id =	18;
update allocation.allocation_data ad set gear_type_id =	700	where ad.gear_type_id =	19;
update allocation.allocation_data ad set gear_type_id =	604	where ad.gear_type_id =	19;
update allocation.allocation_data ad set gear_type_id =	800	where ad.gear_type_id =	19;
update allocation.allocation_data ad set gear_type_id =	401	where ad.gear_type_id =	20;
update allocation.allocation_data ad set gear_type_id =	700	where ad.gear_type_id =	21;
update allocation.allocation_data ad set gear_type_id =	301	where ad.gear_type_id =	21;
update allocation.allocation_data ad set gear_type_id =	302	where ad.gear_type_id =	22;
update allocation.allocation_data ad set gear_type_id =	302	where ad.gear_type_id =	23;
update allocation.allocation_data ad set gear_type_id =	302	where ad.gear_type_id =	24;
update allocation.allocation_data ad set gear_type_id =	302	where ad.gear_type_id =	25;
update allocation.allocation_data ad set gear_type_id =	302	where ad.gear_type_id =	26;
update allocation.allocation_data ad set gear_type_id =	302	where ad.gear_type_id =	27;
update allocation.allocation_data ad set gear_type_id =	302	where ad.gear_type_id =	28;
update allocation.allocation_data ad set gear_type_id =	302	where ad.gear_type_id =	29;
update allocation.allocation_data ad set gear_type_id =	302	where ad.gear_type_id =	30;
update allocation.allocation_data ad set gear_type_id =	302	where ad.gear_type_id =	31;
update allocation.allocation_data ad set gear_type_id =	302	where ad.gear_type_id =	32;
update allocation.allocation_data ad set gear_type_id =	302	where ad.gear_type_id =	33;
update allocation.allocation_data ad set gear_type_id =	302	where ad.gear_type_id =	34;
update allocation.allocation_data ad set gear_type_id =	302	where ad.gear_type_id =	35;
update allocation.allocation_data ad set gear_type_id =	302	where ad.gear_type_id =	36;
update allocation.allocation_data ad set gear_type_id =	302	where ad.gear_type_id =	37;
update allocation.allocation_data ad set gear_type_id =	302	where ad.gear_type_id =	38;
update allocation.allocation_data ad set gear_type_id =	302	where ad.gear_type_id =	39;
update allocation.allocation_data ad set gear_type_id =	500	where ad.gear_type_id =	40;
update allocation.allocation_data ad set gear_type_id =	606	where ad.gear_type_id =	41;
update allocation.allocation_data ad set gear_type_id =	801	where ad.gear_type_id =	41;
update allocation.allocation_data ad set gear_type_id =	700	where ad.gear_type_id =	41;
update allocation.allocation_data ad set gear_type_id =	100	where ad.gear_type_id =	41;
update allocation.allocation_data ad set gear_type_id =	401	where ad.gear_type_id =	41;
update allocation.allocation_data ad set gear_type_id =	601	where ad.gear_type_id =	41;
update allocation.allocation_data ad set gear_type_id =	602	where ad.gear_type_id =	41;
update allocation.allocation_data ad set gear_type_id =	600	where ad.gear_type_id =	42;
update allocation.allocation_data ad set gear_type_id =	401	where ad.gear_type_id =	43;
update allocation.allocation_data ad set gear_type_id =	401	where ad.gear_type_id =	44;
update allocation.allocation_data ad set gear_type_id =	401	where ad.gear_type_id =	45;
update allocation.allocation_data ad set gear_type_id =	401	where ad.gear_type_id =	46;
update allocation.allocation_data ad set gear_type_id =	401	where ad.gear_type_id =	47;
update allocation.allocation_data ad set gear_type_id =	401	where ad.gear_type_id =	48;
update allocation.allocation_data ad set gear_type_id =	401	where ad.gear_type_id =	49;
update allocation.allocation_data ad set gear_type_id =	401	where ad.gear_type_id =	50;
update allocation.allocation_data ad set gear_type_id =	602	where ad.gear_type_id =	51;
update allocation.allocation_data ad set gear_type_id =	301	where ad.gear_type_id =	52;
update allocation.allocation_data ad set gear_type_id =	301	where ad.gear_type_id =	53;
update allocation.allocation_data ad set gear_type_id =	301	where ad.gear_type_id =	54;
update allocation.allocation_data ad set gear_type_id =	401	where ad.gear_type_id =	55;
update allocation.allocation_data ad set gear_type_id =	700	where ad.gear_type_id =	56;
update allocation.allocation_data ad set gear_type_id =	700	where ad.gear_type_id =	57;
update allocation.allocation_data ad set gear_type_id =	700	where ad.gear_type_id =	58;
update allocation.allocation_data ad set gear_type_id =	606	where ad.gear_type_id =	59;
update allocation.allocation_data ad set gear_type_id =	300	where ad.gear_type_id =	60;
update allocation.allocation_data ad set gear_type_id =	710	where ad.gear_type_id =	61;
update allocation.allocation_data ad set gear_type_id =	601	where ad.gear_type_id =	62;
update allocation.allocation_data ad set gear_type_id =	100	where ad.gear_type_id =	63;
update allocation.allocation_data ad set gear_type_id =	200	where ad.gear_type_id =	64;
update allocation.allocation_data ad set gear_type_id =	200	where ad.gear_type_id =	65;
update allocation.allocation_data ad set gear_type_id =	302	where ad.gear_type_id =	66;
update allocation.allocation_data ad set gear_type_id =	302	where ad.gear_type_id =	67;
update allocation.allocation_data ad set gear_type_id =	700	where ad.gear_type_id =	67;
update allocation.allocation_data ad set gear_type_id =	302	where ad.gear_type_id =	68;
update allocation.allocation_data ad set gear_type_id =	302	where ad.gear_type_id =	69;
update allocation.allocation_data ad set gear_type_id =	801	where ad.gear_type_id =	70;
